# Generated by Django 5.2 on 2025-04-24 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='travel_date',
            field=models.DateField(default=datetime.date(2025, 4, 24)),
            preserve_default=False,
        ),
    ]
